export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RANGECHANGE = 'RANGECHANGE'
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TEXT_CHANGE = 'TEXT_CHANGE'
